name: "gigg"

model:
  name: "gigg"
  iters: 10000
  b_init: 1.0
  b_floor: 0.25
  tau_scale: 1.0
  sigma_scale: 1.0
  store_lambda: false

inference:
  gibbs:
    burn_in: 5000
    thin: 1
    jitter: 1.0e-08
    seed: 2025
