name: "grwhs_regression"

model:
  name: "grwhs_gibbs"
  c: 1.0
  eta: 0.7
  tau0: 0.00641500299099584
  s0: 1.0
  iters: 3000

inference:
  gibbs:
    burn_in: 1500
    thin: 1
    jitter: 1.0e-08
    seed: 321
