defaults: "../base.yaml"

name: "logistic_lasso"
task: "classification"

model:
  name: "logistic_regression"
  penalty: "l1"
  solver: "liblinear"
  fit_intercept: true
  max_iter: 500
  tol: 1.0e-5
  search:
    C: [0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0]
