name: "regularized_horseshoe_regression"

model:
  name: "grwhs_gibbs"
  use_groups: false
  c: 1.0
  eta: 0.7
  tau0: 0.00641500299099584
  s0: 1.0
  iters: 10000

inference:
  gibbs:
    burn_in: 5000
    thin: 2
    jitter: 1.0e-08
    seed: 151
