name: "regularized_horseshoe_regression"

model:
  name: "regularized_horseshoe"
  scale_intercept: 10.0
  sigma_scale: 1.0
  slab_scale: 1.0
  tau0: 0.00641500299099584
  num_warmup: 1000
  num_samples: 2000
  num_chains: 1
  thinning: 1
  target_accept_prob: 0.9
  progress_bar: false
  seed: 151
