name: "sparse_group_lasso"

model:
  name: "sparse_group_lasso"
  fit_intercept: false
  max_iter: 100
  max_epochs: 20000
  tol: 1.0e-05
  warm_start: true
  ws_strategy: "fixpoint"
  verbose: 1
  search:
    alpha:
      mode: "logspace"
      start: 1.0
      stop: 0.01
      num: 12
    l1_ratio: [0.4, 0.7]
