name: "toy_regression_overlap_methods"
output_dir: "outputs/sweeps/toy_regression_overlap"

common_config_files:
  - "../experiments/toy_regression.yaml"
  - "../experiments/toy_regression_overlap.yaml"

variations:
  - name: "grwhs_full_overlap"
    config_files:
      - "../methods/grwhs_full.yaml"
  - name: "grwhs_fixed_tau_overlap"
    config_files:
      - "../methods/grwhs_full.yaml"
      - "../methods/grwhs_fixed_tau.yaml"
  - name: "grwhs_no_group_overlap"
    config_files:
      - "../methods/grwhs_no_group.yaml"
  - name: "group_lasso_overlap"
    config_files:
      - "../methods/group_lasso.yaml"
  - name: "sparse_group_lasso_overlap"
    config_files:
      - "../methods/sparse_group_lasso.yaml"
