name: "toy_classification_methods"
output_dir: "outputs/sweeps/toy_classification"

common_config_files:
  - "../experiments/toy_classification.yaml"

variations:
  - name: "grwhs_full_logistic"
    config_files:
      - "../methods/grwhs_full_logistic.yaml"
  - name: "grwhs_fixed_tau_logistic"
    config_files:
      - "../methods/grwhs_full_logistic.yaml"
      - "../methods/grwhs_fixed_tau_logistic.yaml"
  - name: "group_lasso_classification"
    config_files:
      - "../methods/group_lasso.yaml"
  - name: "sparse_group_lasso_classification"
    config_files:
      - "../methods/sparse_group_lasso.yaml"
