name: "toy_regression_methods"
output_dir: "outputs/sweeps/toy_regression"

common_config_files:
  - "../experiments/toy_regression.yaml"

variations:
  - name: "grwhs_full"
    config_files:
      - "../methods/grwhs_full.yaml"
  - name: "grwhs_fixed_tau"
    config_files:
      - "../methods/grwhs_full.yaml"
      - "../methods/grwhs_fixed_tau.yaml"
  - name: "grwhs_no_group"
    config_files:
      - "../methods/grwhs_no_group.yaml"
  - name: "group_lasso"
    config_files:
      - "../methods/group_lasso.yaml"
  - name: "sparse_group_lasso"
    config_files:
      - "../methods/sparse_group_lasso.yaml"
